### ISSUE TITLE
can't load dstu engine

### ISSUE THREAD

**Issue by amindomao** [dstucrypt/dstu-engine#21]
`$ openssl 
OpenSSL> engine dstu
`

`139949105176064:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:118:filename(/usr/lib64/engines-1.1/dstu.so): /usr/lib64/engines-1.1/dstu.so: undefined symbol: EC_GROUP_new_curve_GF2m`

openssl version: OpenSSL 1.1.1q  FIPS 5 Jul 2022

**Comment by madf** [comment]
Same problem as in #19 

Your OpenSSL does not support elliptic curves over binary fields. Probably you use Fedora or some other RedHat derivative. Consider switching to another linux distribution or building OpenSSL manually.

**Comment by amindomao** [comment]
You knew :) Yes, I'm using Fedora. Thanks.
