### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by bogdartysh** [dstucrypt/dstu-engine#9]
Would be nice to have some docker compose image with all needed staff (cmake, make, gcc, openssl) with workable versions to simplify new-commers

**Comment by madf** [comment]
Sounds like a good idea, but I have no experience with Docker, so I would appreciate any help with it.

**Comment by bogdartysh** [comment]
https://github.com/madf/dstu-engine/pull/10

**Comment by madf** [comment]
I merged your pull request. I think it can be closed now, right?

**Comment by bogdartysh** [comment]
ok
